import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

function offlineServiceWorker(): Plugin {
  return {
    name: 'mkar-offline-service-worker',
    async closeBundle() {
      const outDir = join(process.cwd(), 'dist');
      const files = (await readdir(outDir, { recursive: true }))
        .filter((file) => !file.endsWith('sw.js'))
        .map((file) => `/${file.replaceAll('\\', '/')}`)
        .sort();
      const source = `/* Generated by Vite. Do not edit. */
const VERSION = ${JSON.stringify(`mkar-${Date.now()}`)};
const PRECACHE = ${JSON.stringify(files)};
self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(VERSION).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (event) => {
  event.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((key) => key !== VERSION).map((key) => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  const request = event.request;
  event.respondWith(caches.match(request).then((cached) => cached || fetch(request).then((response) => {
    if (response.ok && new URL(request.url).origin === self.location.origin) {
      const copy = response.clone();
      void caches.open(VERSION).then((cache) => cache.put(request, copy));
    }
    return response;
  }).catch(() => caches.match('/'))));
});
`;
      await writeFile(join(outDir, 'sw.js'), source);
    },
  };
}

export default defineConfig({
  plugins: [react(), offlineServiceWorker()],
  build: { sourcemap: true },
});
