[package]
name = "remkar-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ar = "0.9"
aes = "0.8"
cab = "0.6"
cbc = { version = "0.1", features = ["alloc"] }
cipher = { version = "0.4", features = ["alloc"] }
getrandom = { version = "0.2", features = ["js"] }
js-sys = "0.3"
pbkdf2 = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde-wasm-bindgen = "0.6"
sha2 = "0.10"
wasm-bindgen = "0.2"
zstd = "0.13"
oxiarc-archive = { version = "0.4", default-features = false }
oxiarc-core = "0.4"
oxiarc-lzhuf = "0.4"

[dev-dependencies]
base64 = "0.22"
